services:
  zookeeper:
    build: .
    entrypoint: ./bin/zookeeper-server-start.sh ./config/zookeeper.properties
    expose:
      - 2181
    ports:
      - "2181:2181"
  kafka:
    build: .
    entrypoint: ./bin/kafka-server-start.sh ./config/server.properties  --override listeners=PLAINTEXT://kafka:9092 --override advertised.listeners=PLAINTEXT://kafka:9092
    expose:
      - 9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  requester.services:
    build:
      context: .
      dockerfile: ./DockerfileApp
    environment:
      server.port: 8080
    entrypoint: /opt/app/start-service.sh ./lib/es-jambo-command-request-0.0.1-SNAPSHOT.jar
    volumes:
      - ./es-jambo-command-request/target:/opt/app/lib
    expose:
      - 8080
    ports:
      - "8080-8085:8080"
    scale: 3
    depends_on:
      - kafka
  response.services:
    build:
      context: .
      dockerfile: ./DockerfileApp
    environment:
      nodename: "response.server.2"
      server.port: 8090
    entrypoint: /opt/app/start-service.sh  ./lib/es-jambo-command-response-0.0.1-SNAPSHOT.jar
    volumes:
      - ./es-jambo-command-response/target:/opt/app/lib
    scale: 3
    ports:
      - "8090-8095:8090"
    depends_on:
      - kafka