version: "3"
services:
  zookeeper:
    build: .
    entrypoint: ./bin/zookeeper-server-start.sh ./config/zookeeper.properties
    expose:
      - 2181
    ports:
      - "2181:2181"
  kafka:
    build: .
    entrypoint: ./bin/kafka-server-start.sh ./config/server.properties  --override listeners=PLAINTEXT://kafka:9092 --override advertised.listeners=PLAINTEXT://kafka:9092
    expose:
      - 9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  requester.service.1:
    build:
      context: .
      dockerfile: ./DockerfileApp
    environment:
      nodename: "request.server.1"
      server.port: 8080
      kafka.topic.command.response: "topic.server.request.1"
    entrypoint: java -jar es-jambo-command-request-0.0.1-SNAPSHOT.jar
    volumes:
      - ./es-jambo-command-request/target:/opt/app
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - kafka
  requester.service.2:
    build:
      context: .
      dockerfile: ./DockerfileApp
    environment:
      nodename: "request.server.2"
      server.port: 8081
      kafka.topic.command.response: "topic.server.request.2"
    entrypoint: java -jar es-jambo-command-request-0.0.1-SNAPSHOT.jar
    volumes:
      - ./es-jambo-command-request/target:/opt/app
    expose:
      - 8081
    ports:
      - "8081:8081"
    depends_on:
      - kafka
  response.service.1:
    build:
      context: .
      dockerfile: ./DockerfileApp
    environment:
      nodename: "response.server.1"
      server.port: 8082
    entrypoint: java -jar es-jambo-command-response-0.0.1-SNAPSHOT.jar
    volumes:
      - ./es-jambo-command-response/target:/opt/app
    expose:
      - 8082
    ports:
      - "8082:8082"
    depends_on:
      - kafka
  response.service.2:
    build:
      context: .
      dockerfile: ./DockerfileApp
    environment:
      nodename: "response.server.2"
      server.port: 8083
    entrypoint: java -jar es-jambo-command-response-0.0.1-SNAPSHOT.jar
    volumes:
      - ./es-jambo-command-response/target:/opt/app
    expose:
      - 8083
    ports:
      - "8083:8083"
    depends_on:
      - kafka